### ISSUE TITLE
WFLYCTL0180: Services with missing/unavailable dependencies

### ISSUE THREAD

**Issue by jens-stahl** [openshift-s2i/s2i-wildfly#106]
Starting wildfly I get the following error event though I have not changed anything regarding email service:

[0m [31m12:10:28,051 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "mail"),
    ("mail-session" => "default")
]) - failure description: {"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.mail-session.default is missing [jboss.outbound-socket-binding.mail-smtp]"]}

**Comment by bparees** [comment]
can you give more details of your scenario?  how are you running the image?  did you build an image using s2i?  exact recreate steps would be useful.

**Comment by jens-stahl** [comment]
I have created a service via https://console.preview.openshift.com/console:
apiVersion: v1
kind: Service
metadata:
  name: wildfly-10
  namespace: worldportfolio
  selfLink: /api/v1/namespaces/worldportfolio/services/wildfly-10
  uid: 779b2ecf-7e53-11e6-b578-0ebeb1070c7f
  resourceVersion: '173771676'
  creationTimestamp: '2016-09-19T10:26:03Z'
  labels:
    app: wildfly-10
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  ports:
    -
      name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentconfig: wildfly-10
  portalIP: 172.30.140.48
  clusterIP: 172.30.140.48
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {  }

I have then deployed a JSF application which runs on other Wildflys without issues. During startup I receive the above mentioned error. (E-Mails sending is not affected though my application is able to send mails)

**Comment by bparees** [comment]
it sounds like you're saying you build a new wildfly app by selecting the wildfly image from the web console and then specified your own git repo containing a JSF application to be built.

Is that correct?

Is the git repo containing that application public so i can look at it?

**Comment by bparees** [comment]
ok i was able to recreate the issue, https://github.com/openshift-s2i/s2i-wildfly/pull/107 will fix it.

**Comment by jens-stahl** [comment]
Great, thanks! (I'm not allowed to share my JSF application, it is hosted privately)
