### ISSUE TITLE
SSH git issue

### ISSUE THREAD

**Issue by kenk667** [openshift-s2i/s2i-wildfly#110]
Hello;

I'm having issues with a build using openshift/wildfly:latest which is 101 centos 7. I have my git pull setup to use a SSH secret in the buildconfig. I've tested the git pull to the host and it works fine, but when I start a build, it fails with this;

110 19:27:43.884627       1 glog.go:50] git ls-remote --heads ssh://git@bitbucket..some.domain:7999/jbosp/jbossservletpost.git
I1110 19:27:43.884666       1 repository.go:355] Executing GIT_ASKPASS=true GIT_SSH=/tmp/gitssh261142345 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=jbossservletpost-25-build BUILD={"kind":"Build","apiVersion":"v1","metadata":{"name":"jbossservletpost-25","namespace":"test3","selfLink":"/oapi/v1/namespaces/test3/builds/jbossservletpost-25","uid":"8e6aec3b-a77b-11e6-a79d-005056ad4f06","resourceVersion":"142968","creationTimestamp":"2016-11-10T19:26:19Z","labels":{"app":"jbossservletpost","buildconfig":"jbossservletpost","openshift.io/build-config.name":"jbossservletpost","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"jbossservletpost","openshift.io/build.number":"25"}},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"ssh://git@bitbucket.some.domain:7999/jbosp/jbossservletpost.git"},"sourceSecret":{"name":"sshsecret"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"openshift/wildfly-101-centos7@sha256:7f0aa3a6adeeaa6c0d28a8ce04dffacb3416008d32852c2d635cb60e64354724"},"env":[{"name":"BUILD_LOGLEVEL","value":"5"}]}},"output":{"to":{"kind":"DockerImage","name":"172.30.123.234:5000/test3/jbossservletpost:latest"},"pushSecret":{"name":"builder-dockercfg-evbi8"}},"resources":{},"postCommit":{},"triggeredBy":[{"message":"Manually triggered"}]},"status":{"phase":"New","outputDockerImageReference":"172.30.123.234:5000/test3/jbossservletpost:latest","config":{"kind":"BuildConfig","namespace":"test3","name":"jbossservletpost"}}}
 SOURCE_REPOSITORY=ssh://git@bitbucket.some.domain:7999/jbosp/jbossservletpost.git SOURCE_URI=ssh://git@bitbucket.some.domain:7999/jbosp/jbossservletpost.git ORIGIN_VERSION=v1.3.1 BUILD_LOGLEVEL=5 ALLOWED_UIDS=1- DROP_CAPS=KILL,MKNOD,SETGID,SETUID,SYS_CHROOT PUSH_DOCKERCFG_PATH=/var/run/secrets/openshift.io/push SOURCE_SECRET_PATH=/var/run/secrets/openshift.io/source KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443 JBOSSSERVLETPOST_SERVICE_PORT=8080 JBOSSSERVLETPOST_PORT_8080_TCP_PROTO=tcp JBOSSSERVLETPOST_PORT_8080_TCP_ADDR=172.30.46.73 KUBERNETES_PORT_443_TCP_PROTO=tcp KUBERNETES_PORT_443_TCP_PORT=443 KUBERNETES_PORT_53_UDP_PROTO=udp KUBERNETES_PORT_53_UDP_ADDR=172.30.0.1 KUBERNETES_PORT_53_TCP=tcp://172.30.0.1:53 KUBERNETES_PORT_53_TCP_ADDR=172.30.0.1 KUBERNETES_SERVICE_HOST=172.30.0.1 KUBERNETES_SERVICE_PORT_HTTPS=443 KUBERNETES_SERVICE_PORT_DNS=53 KUBERNETES_PORT=tcp://172.30.0.1:443 KUBERNETES_PORT_53_UDP=udp://172.30.0.1:53 KUBERNETES_PORT_53_UDP_PORT=53 KUBERNETES_PORT_53_TCP_PROTO=tcp KUBERNETES_PORT_53_TCP_PORT=53 JBOSSSERVLETPOST_SERVICE_HOST=172.30.46.73 JBOSSSERVLETPOST_SERVICE_PORT_8080_TCP=8080 JBOSSSERVLETPOST_PORT_8080_TCP_PORT=8080 KUBERNETES_SERVICE_PORT=443 KUBERNETES_SERVICE_PORT_DNS_TCP=53 KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1 JBOSSSERVLETPOST_PORT=tcp://172.30.46.73:8080 JBOSSSERVLETPOST_PORT_8080_TCP=tcp://172.30.46.73:8080 HOME=/root OPENSHIFT_CONTAINERIZED=true KUBECONFIG=/var/lib/origin/openshift.local.config/master/admin.kubeconfig git ls-remote --heads ssh://git@bitbucket.some.domain:7999/jbosp/jbossservletpost.git
I1110 19:29:51.135259       1 repository.go:423] Error executing command: exit status 128
I1110 19:29:51.135339       1 glog.go:50] ssh: connect to host bitbucket..some.domain port 7999: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
I1110 19:29:51.135371       1 cleanup.go:33] Removing temporary directory /tmp/s2i-build055089684
I1110 19:29:51.135390       1 fs.go:159] Removing directory '/tmp/s2i-build055089684'
F1110 19:29:51.135645       1 helpers.go:110] error: build error: ssh: connect to host bitbucket.some.domain port 7999: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I've turned firewalld off to eliminate FW issues, what am I missing?

thanks;

Ken

**Comment by bparees** [comment]
can you try flushing your iptables rules?  (iptables -F)

if you run a generic pod (like a db pod) and `oc rsh` into it, are you able to make external connections from within that pod?

**Comment by kenk667** [comment]
@bparees 
thanks for posting, host is CentOS 7 so it's firewalld, not iptables for me. And I should have been clear on my first post, I'.m running openshift origin, oc verison results are:
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.206.73.131:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

**Comment by bparees** [comment]
firewalld is a higher level than iptables, you may still need to flush your iptables.

but certainly try the other debug step i proposed first.

you can also run `oc adm diagnostics`

**Comment by kenk667** [comment]
just flushed iptables and am building a db pod as I type now

**Comment by kenk667** [comment]
oc adm diagnostics completes with no errors or warnings

**Comment by kenk667** [comment]
tried to ping bitbucket by name, no response, but get a response from pinging the IP, which points to a DNS issue. Troubleshooting DNS set up within container? I thought that the container defaulted to the host's resolv.conf file? Right now the resolv.conf within the db container lists the host ip as the DNS authority

**Comment by bparees** [comment]
are you running dnsmasq?  that could be interfering, openshift attempts to stand up its own local dns.

**Comment by bparees** [comment]
(adm diagnostic should have caught an issue like that, though.  it may be worth opening an issue against openshift/origin if that turns out to be the problem)

**Comment by kenk667** [comment]
I didn't install and setup dnsmasq, so it should be using skydns. I can run dig command within the pod and get an answer for the bitbucket server I'm trying to reach, but cant't ping it by by name. This morning I can't even ping the bitbucket host by IP which reside in another subnet, but can reach it via ping from the host.

**Comment by bparees** [comment]
ok, can you open this issue against openshift/origin and i can get the right folks tagged in to help diagnose your network issues?

**Comment by kenk667** [comment]
Thank you ben, I just opened an issue in openshift/origin;

Pod networking and DNS issues #11920
