### ISSUE TITLE
Please allow for spec subsitution

### ISSUE THREAD

**Issue by thesteve0** [openshift-s2i/s2i-wildfly#111]
It would be really great if we could change this line to allow for spec substitution inside spec files like persistence.xml

https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.1/contrib/wfcfg/standalone.xml#L193

This would allow developer to use ENV variable subsitution if they didn't want to load their own standalone.xml and then do JNDI work. 

http://www.mastertheboss.com/jboss-frameworks/hibernate-jpa/jpa-configuration/how-to-use-an-env-variable-in-your-persistencexml

**Comment by bparees** [comment]
@thesteve0 will do.
