### ISSUE TITLE
Custom default datasource (ExampleDS)

### ISSUE THREAD

**Issue by carlosthe19916** [openshift-s2i/s2i-wildfly#125]
Hi. Sometime is necessary to use custom datasource name. Right now I can do that using the mysql or postgres datasource, but what about custom datasource names without needing a database; what I'm saying is I think that the default datasource Example DS should be customizable by an environment variable.

What do you think about that?

**Comment by bparees** [comment]
The current assumption is that if you need to customize more than what the default standalone.xml template allows for, you just provide your own standalone.xml w/ your application.  The s2i builder allows for that.

But if you want to submit a PR that makes the example DS name configurable via env variable, we'd accept it.

**Comment by carlosthe19916** [comment]
My point of view is that for a trivial change like the default datasource name is not necesary put a custom standalone.xml...

Maybe is not the best solution for this but this is a pull request for custom datasource name #127
