### ISSUE TITLE
Doc about datasource wrong

### ISSUE THREAD

**Issue by adrianbader** [openshift-s2i/s2i-wildfly#136]
It is written in readme.md:

> ...
> POSTGRESQL_DATABASE
> If set, WildFly will attempt to define a PostgreSQL datasource based on the assumption you have an OpenShift service named "postgresql" defined...

This is wrong. The created datasource is **PostgreSQLDS** rather than _postgresql_

**Comment by bparees** [comment]
the description isn't intended to be taken as the literal name of the datasource.  it is a datasource for a postgresql db, hence "a PostgreSQL datasource" and not "a datasource named PostgreSQL".

the datasource name is actually configurable:
```
 if [ -n "$POSTGRESQL_DATASOURCE" ]
  then
    export OPENSHIFT_POSTGRESQL_DATASOURCE=$POSTGRESQL_DATASOURCE
  else
    export OPENSHIFT_POSTGRESQL_DATASOURCE="PostgreSQLDS"
  fi
```
