### ISSUE TITLE
outdated postgresql driver

### ISSUE THREAD

**Issue by adrianbader** [openshift-s2i/s2i-wildfly#137]
If I use a porstgres datasource, an outdated driver will be taken:
> [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 33) WFLYJCA0005: 
Deploying non-JDBC-compliant driver class org.postgresql.Driver (version 8.4)

Where and how can I setup, which driver to take?

**Comment by bparees** [comment]
the driver is here:
https://github.com/openshift-s2i/s2i-wildfly/tree/master/10.1/contrib/wfmodules/org/postgresql/jdbc/main

you can submit a PR to update it to a newer driver if you'd like.

Barring that, you can provide your own modules (but i'm not sure if they'll overwrite the ones included in the image) as part of your application:
https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.1/s2i/bin/assemble#L340-L346

**Comment by adrianbader** [comment]
> Barring that, you can provide your own modules
As I see, the modules folder is copied to /wildfly/provided_modules. I am not able to bring wildfly to load the driver from there. Is wildfly really use this folder to search modules in there? I tried it locally, it seems a _provided_modules_ folder is ignored and I cannot find any hint in the wildfly doc about such a folder. Anyhow, I must miss something...

**Comment by bparees** [comment]
https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.1/contrib/wfbin/standalone.conf#L180

**Comment by bparees** [comment]
https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.1/contrib/wfbin/standalone.conf#L180-L186

**Comment by bparees** [comment]
since we put provided_modules first, your module should get picked up before the existing one.
