### ISSUE TITLE
Pass JVM parameters to wildfly

### ISSUE THREAD

**Issue by adrianbader** [openshift-s2i/s2i-wildfly#139]
I should be able to pass arguments (e.g. -javaagent) to the JVM started for wildfly. Am I right that there is currently no way to do so? Or can we do that by setting env. var JAVA_OPTS?
I am not very familiar with all these yet...
Thanks for a tip :)

**Comment by bparees** [comment]
you can set JAVA_OPTS, but note that if you set JAVA_OPTS, whatever you set will completely replace the default settings as seen here:
https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.1/contrib/wfbin/standalone.conf#L169-L174

so when you set it, you will need to set any of those existing values that still make sense for you.

alternatively you can set JAVA_OPTS_EXT which just appends to the existing options:
https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.1/contrib/wfbin/standalone.conf#L176-L178

**Comment by adrianbader** [comment]
Thank you very much for your quick and perfect answers!

**Comment by bparees** [comment]
yw
