### ISSUE TITLE
JSP utf8

### ISSUE THREAD

**Issue by speedfl** [openshift-s2i/s2i-wildfly#143]
Hello,

Do you maybe know how can I do to keep utf8 working

In local I have no issues but with the s2i when I put my jsp with accents I am getting ```??```

For exemple:
```Confidentialité ``` becomes ```Confidentialit??```

**Comment by bparees** [comment]
This page suggests you check the wildfly configuration:
https://stackoverflow.com/questions/31205287/encoding-servlets-with-utf-8-on-wildfly

by default the standalone.xml in the wildfly image has no encoding specified:
https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.1/contrib/wfcfg/standalone.xml#L394-L415

so you'll need to supply your own standalone.xml if you want to change it.

**Comment by speedfl** [comment]
I already use my own configuration on the domain.xml but the encoding was not set I will try with this first then with standalone and I will let you know
