### ISSUE TITLE
Ability to override standalone.xml?

### ISSUE THREAD

**Issue by lcollet** [openshift-s2i/s2i-wildfly#149]
Is it possible to create a S2I that allow the override of the standalone.xml by our own?
You did a great work with this image but i want to remove some modules i don't need.
Should i copy this S2I and modify it by myself or is it possible that you deal with your script to allow the override?

Maybe there's points i misunderstood?

Regards.

**Comment by bparees** [comment]
if you put a standalone.xml in a dir named "cfg" within your git repo, it should be copied into the wildfly server's config dir during assembly:
https://github.com/openshift-s2i/s2i-wildfly/blob/master/11.0/s2i/bin/assemble#L333-L338
