### ISSUE TITLE
Remote debug

### ISSUE THREAD

**Issue by speedfl** [openshift-s2i/s2i-wildfly#175]
Hello,

Is there a way to allow remote debug ?

Best regards

**Comment by bparees** [comment]
you can enable it by setting ENABLE_JPDA to a non-empty string value:
https://github.com/openshift-s2i/s2i-wildfly/blob/master/14.0/contrib/wfbin/standalone.conf#L171

**Comment by speedfl** [comment]
Thanks I will try
