### ISSUE TITLE
JDK11 Wfly 15 Image 

### ISSUE THREAD

**Issue by neoludo** [openshift-s2i/s2i-wildfly#181]
I'm a bit surprised of the lack of JDK 11 support.
Do you plan to release an image for it ?

Thanks
Ludo

**Comment by bparees** [comment]
Sorry, maintaining this image isn't the top of my priorities these days.  I've created a PR to move it to jdk11 here:
https://github.com/openshift-s2i/s2i-wildfly/pull/182

**Comment by neoludo** [comment]
Great, thanks for the PR

Ludo

Le mar. 5 févr. 2019 à 15:40, Ben Parees <notifications@github.com> a
écrit :
