### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ajdevries** [openshift-s2i/s2i-wildfly#82]
Hi, 

I build a s2i image for apps that can be build with `gradle`. Works okay in openshift v3, but I can't get the `save-artifacts` working.

Maybe not the right place to create an issue, but wondering if @bparees can help me here. Copied most of the scripts from the `wildfly` version.

Code is over here: https://github.com/ajdevries/sti-gradle

**Comment by bparees** [comment]
Can you tell me what issue you're having w/ save-artifacts?

**Comment by ajdevries** [comment]
When starting a new build. Gradle is downloading all artifacts again. So I think that the artifacts are not restored. Is there a way to test this or figure out what is happening before a build starts.

**Comment by bparees** [comment]
well if you run s2i with --loglevel=5 it reports all the files it is tarring up, based on what was git-cloned and save-artifact'd.

you can also run with "--save-temp-dir" which will leave the working directory around so you can inspect the files that exist there.  you should expect to see:
1) the cloned git repo
2) anything returned by save-artifacts.

are you sure gradle is putting the files in the ~/.m2 directory?  that is all your current save-artifacts script is preserving.

also you need to ensure your assemble script restores the files to the correct location, eg: https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.0/s2i/bin/assemble#L10-L15

**Comment by ajdevries** [comment]
wow, thanks this is helpful. Seeing that one commit is missing in the repo. But wil test with loglevel first!

**Comment by ajdevries** [comment]
Push the latest changes to the repo. Tested a little bit more, but it's not working. In the temp dir there is only the cloned git repo.

**Comment by bparees** [comment]
I guess i should have asked the obvious question first...  you're running with --incremental=true and you have a previous version of the output image available locally?

**Comment by ajdevries** [comment]
Hmm, that's a good one. Can't test with incremental, but discovered that openshift BuildConfig was missing the incremental property. Testing this right now, thanks for the help.

Is it interesting to add a gradle build to this repo (and openshift?)

**Comment by bparees** [comment]
Yeah I'd be happy to accept a pull that adds gradle support to the s2i
wildfly image.

**Comment by ajdevries** [comment]
It should be a standalone s2i image, so a separate repo I guess. Because it is starting apps with java -jar

**Comment by bparees** [comment]
sure, if you're going to just build and run a standalone java app, that would be a separate s2i java image.

note that there is already a standalone java s2i image (though it also is maven based):
https://docs.openshift.org/latest/using_images/s2i_images/java.html
https://github.com/fabric8io/java-main/tree/master/
