### ISSUE TITLE
No .ear, .jar, .ejb support

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-s2i/s2i-wildfly#91]
Wildfly support many other types of applications to be deployed, like .ear, .ejb, .jar and the s2i image does not allow for it.

**Comment by bparees** [comment]
@jorgemoralespou any chance you can do a PR for this?  it'll get done faster if you do :)

**Comment by jorgemoralespou** [comment]
@bparees If I get some free cycles I will. I'll add it to my todo list.

**Comment by bparees** [comment]
thanks!

On Wed, Jun 15, 2016 at 8:50 AM, Jorge Morales Pou <notifications@github.com
> wrote:

> @bparees <https://github.com/bparees> If I get some free cycles I will.
> I'll add it to my todo list.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift-s2i/s2i-wildfly/issues/91#issuecomment-226231121>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEvl3owdYKV8K9-zkei0MYEKgij_TL9Qks5qMB9CgaJpZM4I2U7e>
> .
>



-- 
Ben Parees | OpenShift
